version: 2

models:
  - name: stg_customers
    description: Staged customer data from the raw database.
    columns:
      - name: customer_id
        description: Primary key for customers.
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer first name
      - name: last_name
        description: Customer last name
      - name: email
        description: Customer email address
        tests:
          - not_null

  - name: stg_orders
    description: Staged order data from the raw database.
    columns:
      - name: order_id
        description: Primary key for orders.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers table
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        description: Date of the order
      - name: status
        description: Order status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'returned', 'cancelled']